const models = require ('../../models/index');
module.exports={
    up:(queryInterface,Sequelize)=>{
        return queryInterface.sequelize.transaction(t=>{
			let promise=[
			models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001816_audio",
PhotoFormat:"jpeg"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:1}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001875_speaker",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:11}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001615_amplifier",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:12}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001616_sub-woofer",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:13}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001617_microphone",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:14}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001618_sound-processors",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:15}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001653_karaoke-speakers",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:21}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001652_professional-speakers",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:22}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001628_power-amplifiers",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:23}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001622_csv-series",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:24}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001623_csd-series",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:25}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001624_csx-series",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:26}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001625_csn-series",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:27}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001626_csj-series",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:28}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001627_csp-series",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:29}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001636_dap-series",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:30}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001674_pr-series",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:31}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001675_pv-series",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:32}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/000564_hroothomeaungwin92-002wwwconeicstorepluginssevenspikesnoppluginsproductribbonsribbonpicturesmotion_l",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:33}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001676_sp-series",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:34}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001677_qw-series",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:35}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001678_vr-series",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:40}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001637_cs-series",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:41}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001638_pv-series",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:42}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001639_ipr-2-series",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:43}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001619_non-powered-mixers",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:44}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001620_powered-mixers",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:45}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001644_pv-series",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:46}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001645_fx-2-series",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:47}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001646_pv-series",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:48}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001647_xr-series",
PhotoFormat:"jpeg"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:49}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001648_pvi-series",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:50}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001621_public-address-systems",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:51}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001649_escort-system",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:52}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001629_guitar-amplifiers",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:55}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001641_vypyr-vip-series",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:56}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001642_valveking-series",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:57}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001630_bass-amplifiers",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:58}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001643_tour-series",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:59}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001631_keyboard-amplifiers",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:60}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001632_crest-amplifiers",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:61}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001651_pvi-portable-series",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:62}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001744_pvx-series",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:63}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001793_cc-series",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:65}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001794_cpx-series",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:66}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001792_nkn-series",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:67}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001795_vr-series",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:68}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001796_pv-series",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:69}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001797_pr-series",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:70}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001799_csw-series",
PhotoFormat:"jpeg"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:71}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001805_pvm-series",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:72}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001817_processing-and-effects",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:73}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001869_crossovers",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:74}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001814_pvm-dms-5-drum-mic-system",
PhotoFormat:"jpeg"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:75}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001815_karaoke-amplifier",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:76}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001823_pvx-series",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:77}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001840_spare-parts",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:80}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001841_rx-22-22-xt",
PhotoFormat:"jpeg"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:81}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001845_high-fz-drivers",
PhotoFormat:"jpeg"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:82}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001871_triflex-ii",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:83}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001883_equalizer",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:84}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001881_instrument-amplifiers",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:85}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001866_consumer-electronics",
PhotoFormat:"jpeg"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:87}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001867_bluetooth",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:88}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001882_processors",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:89}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0002128_pbk-series",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:90}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001892_infrared-microphone",
PhotoFormat:"jpeg"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:93}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0001902_cse-series",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:94}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0002038_ceiling-wall-speakers",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:100}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0002037_phr-series",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:102}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0002036_ws-series",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:103}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0002045_css-series",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:107}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0002060_accessories",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:108}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0002061_headphones",
PhotoFormat:"jpeg"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:109}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0002059_low-fz-drivers",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:110}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0002127_dark-matter-series",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:114}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0002110_qw-series",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:116}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0002155_home-category",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:122}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0002183_electric",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:124}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0002182_bass",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:125}}),
models.ProductGroup.update({
Photo:"shopkeeper/productgroup/0002181_acoustic",
PhotoFormat:"png"},{fields:["Photo","PhotoFormat"],transaction:t,where:{id:126}}),
			];
			return Promise.all(promise);
		});
    },
    down:(queryInterface,Sequelize)=>{
        return models.ProductGroup.destroy({truncate:true,cascade:true});
    }
};
